// Generated by rocketdb: Do not edit this code!

import {Configuration as concrete_Configuration} from '../Configuration';
import * as Long from 'long';

export abstract class Configuration {

    public static readonly __typeId: string = "38f9941c-5d29-11e9-91b2-4b4f2bb00878";
    public static readonly __typeName: string = "pharmacy.module.Configuration";

    private _____domainId: string = null;
    private _____ownerId: string = null;
    private _____creatorId: string = null;
    private _____state: string = null;
    private _____operation: string = null;
    private _____tts: Long = null;
    private _____sequence: number = null;
    private _____ttsTo: Long = null;
    private _____id: string = null;
    private _____moduleId: string = null;
    private _____name: string = null;
    private _____active: boolean = null;

    public get __typeId(): string {
        return Configuration.__typeId;
    }

    public get __typeName(): string {
        return Configuration.__typeName;
    }

    public get __domainId(): string {
        return this._____domainId;
    }

    public set __domainId(value: string) {
        this._____domainId = value;
    }

    public get __ownerId(): string {
        return this._____ownerId;
    }

    public set __ownerId(value: string) {
        this._____ownerId = value;
    }

    public get __creatorId(): string {
        return this._____creatorId;
    }

    public set __creatorId(value: string) {
        this._____creatorId = value;
    }

    public get __state(): string {
        return this._____state;
    }

    public set __state(value: string) {
        this._____state = value;
    }

    public get __operation(): string {
        return this._____operation;
    }

    public set __operation(value: string) {
        this._____operation = value;
    }

    public get __tts(): Long {
        return this._____tts;
    }

    public set __tts(value: Long) {
        this._____tts = value;
    }

    public get __sequence(): number {
        return this._____sequence;
    }

    public set __sequence(value: number) {
        this._____sequence = value;
    }

    public get __ttsTo(): Long {
        return this._____ttsTo;
    }

    public set __ttsTo(value: Long) {
        this._____ttsTo = value;
    }

    public get __id(): string {
        if (this._____id === null) {this._____id = this.createId();}
        return this._____id;
    }

    public set __id(value: string) {
        this._____id = value;
    }

    public get __moduleId(): string {
        return this._____moduleId;
    }

    public set __moduleId(value: string) {
        this._____moduleId = value;
    }

    public get __name(): string {
        return this._____name;
    }

    public set __name(value: string) {
        this._____name = value;
    }

    public get __active(): boolean {
        return this._____active;
    }

    public set __active(value: boolean) {
        this._____active = value;
    }

    protected createId(): string {
        var UUID = require('uuid-js');
        return UUID.create(1);
    }

    public static fromJson (json: {}):concrete_Configuration {
        if (!json) return null;

        let object = new concrete_Configuration();
        object.setJson(json);

        return object;
    }

    protected setJson (json: {}): void {
        if (json) {
            this.__domainId = json['__domainId'] != null ? json['__domainId'] : null;
            this.__ownerId = json['__ownerId'] != null ? json['__ownerId'] : null;
            this.__creatorId = json['__creatorId'] != null ? json['__creatorId'] : null;
            this.__state = json['__state'] != null ? json['__state'] : null;
            this.__operation = json['__operation'] != null ? json['__operation'] : null;
            this.__tts = json['__tts'] != null ? Long.fromString(json['__tts']) : null;
            this.__sequence = json['__sequence'] != null ? json['__sequence'] : null;
            this.__ttsTo = json['__ttsTo'] != null ? Long.fromString(json['__ttsTo']) : null;
            this.__id = json['__id'] != null ? json['__id'] : null;
            this.__moduleId = json['__moduleId'] != null ? json['__moduleId'] : null;
            this.__name = json['__name'] != null ? json['__name'] : null;
            this.__active = json['__active'] != null ? json['__active'] : null;
        }
    }

    protected writeJsonMembers(json: {}): void {
        {
            json['__tts'] = this.__tts !== null ? this.__tts.toString() : null;
        }
        {
            json['__id'] = this.__id;
        }
        {
            json['__moduleId'] = this.__moduleId;
        }
        {
            json['__name'] = this.__name;
        }
        {
            json['__active'] = this.__active;
        }
    }

    public toJson(injectType?:boolean): {} {
        let json = {};
        json['__typeId'] = this.__typeId;
        this.writeJsonMembers(json);
        return json;
    }

    public toString(): string {
        return JSON.stringify(this.toJson());
    }

}
