// Generated by rocketdb: Do not edit this code!

import {BaseMedication as concrete_BaseMedication} from '../BaseMedication';
import * as Long from 'long';

export abstract class BaseMedication {

    public static readonly __typeId: string = "9793b078-acae-11e9-85a0-39552ea1958a";
    public static readonly __typeName: string = "pharmacy.BaseMedication";

    private _____domainId: string = null;
    private _____ownerId: string = null;
    private _____creatorId: string = null;
    private _____state: string = null;
    private _____operation: string = null;
    private _____tts: Long = null;
    private _____sequence: number = null;
    private _____ttsTo: Long = null;
    private ___id: string = null;
    private ___pharmacode: string = null;
    private ___name: string = null;
    private ___price: number = null;
    private ___ean: string = null;
    private ___lastUpdate: string = null;
    private ___isActive: boolean = null;
    private ___basedOnIds: string[] = [];

    public get __typeId(): string {
        return BaseMedication.__typeId;
    }

    public get __typeName(): string {
        return BaseMedication.__typeName;
    }

    public get __domainId(): string {
        return this._____domainId;
    }

    public set __domainId(value: string) {
        this._____domainId = value;
    }

    public get __ownerId(): string {
        return this._____ownerId;
    }

    public set __ownerId(value: string) {
        this._____ownerId = value;
    }

    public get __creatorId(): string {
        return this._____creatorId;
    }

    public set __creatorId(value: string) {
        this._____creatorId = value;
    }

    public get __state(): string {
        return this._____state;
    }

    public set __state(value: string) {
        this._____state = value;
    }

    public get __operation(): string {
        return this._____operation;
    }

    public set __operation(value: string) {
        this._____operation = value;
    }

    public get __tts(): Long {
        return this._____tts;
    }

    public set __tts(value: Long) {
        this._____tts = value;
    }

    public get __sequence(): number {
        return this._____sequence;
    }

    public set __sequence(value: number) {
        this._____sequence = value;
    }

    public get __ttsTo(): Long {
        return this._____ttsTo;
    }

    public set __ttsTo(value: Long) {
        this._____ttsTo = value;
    }

    public get id(): string {
        if (this.___id === null) {this.___id = this.createId();}
        return this.___id;
    }

    public set id(value: string) {
        this.___id = value;
    }

    public get pharmacode(): string {
        return this.___pharmacode;
    }

    public set pharmacode(value: string) {
        this.___pharmacode = value;
    }

    public get name(): string {
        return this.___name;
    }

    public set name(value: string) {
        this.___name = value;
    }

    public get price(): number {
        return this.___price;
    }

    public set price(value: number) {
        this.___price = value;
    }

    public get ean(): string {
        return this.___ean;
    }

    public set ean(value: string) {
        this.___ean = value;
    }

    public get lastUpdate(): string {
        return this.___lastUpdate;
    }

    public set lastUpdate(value: string) {
        this.___lastUpdate = value;
    }

    public get isActive(): boolean {
        return this.___isActive;
    }

    public set isActive(value: boolean) {
        this.___isActive = value;
    }

    public get basedOnIds(): string[] {
        return this.___basedOnIds;
    }

    public set basedOnIds(value: string[]) {
        this.___basedOnIds = value !== null ? value : [];
    }

    protected createId(): string {
        var UUID = require('uuid-js');
        return UUID.create(1);
    }

    public static fromJson (json: {}):concrete_BaseMedication {
        if (!json) return null;

        let object = new concrete_BaseMedication();
        object.setJson(json);

        return object;
    }

    protected setJson (json: {}): void {
        if (json) {
            this.__domainId = json['__domainId'] != null ? json['__domainId'] : null;
            this.__ownerId = json['__ownerId'] != null ? json['__ownerId'] : null;
            this.__creatorId = json['__creatorId'] != null ? json['__creatorId'] : null;
            this.__state = json['__state'] != null ? json['__state'] : null;
            this.__operation = json['__operation'] != null ? json['__operation'] : null;
            this.__tts = json['__tts'] != null ? Long.fromString(json['__tts']) : null;
            this.__sequence = json['__sequence'] != null ? json['__sequence'] : null;
            this.__ttsTo = json['__ttsTo'] != null ? Long.fromString(json['__ttsTo']) : null;
            this.id = json['id'] != null ? json['id'] : null;
            this.pharmacode = json['pharmacode'] != null ? json['pharmacode'] : null;
            this.name = json['name'] != null ? json['name'] : null;
            this.price = json['price'] != null ? json['price'] : null;
            this.ean = json['ean'] != null ? json['ean'] : null;
            this.lastUpdate = json['lastUpdate'] != null ? json['lastUpdate'] : null;
            this.isActive = json['isActive'] != null ? json['isActive'] : null;
            this.basedOnIds = json['basedOnIds'] != null ? json['basedOnIds'] : [];
        }
    }

    protected writeJsonMembers(json: {}): void {
        {
            json['__tts'] = this.__tts !== null ? this.__tts.toString() : null;
        }
        {
            json['id'] = this.id;
        }
        {
            json['pharmacode'] = this.pharmacode;
        }
        {
            json['name'] = this.name;
        }
        {
            json['price'] = this.price;
        }
        {
            json['ean'] = this.ean;
        }
        {
            json['lastUpdate'] = this.lastUpdate;
        }
        {
            json['isActive'] = this.isActive;
        }
        {
            json['basedOnIds'] = this.basedOnIds;
        }
    }

    public toJson(injectType?:boolean): {} {
        let json = {};
        json['__typeId'] = this.__typeId;
        this.writeJsonMembers(json);
        return json;
    }

    public toString(): string {
        return JSON.stringify(this.toJson());
    }

}
