// Generated by rocketdb: Do not edit this code!

import {Patients as concrete_Patients} from '../Patients';
import * as Long from 'long';

export abstract class Patients {

    public static readonly __typeId: string = "7612e163-acb4-11e9-8fb9-9dd57dcb9b05";
    public static readonly __typeName: string = "pharmacy.Patients";

    private _____domainId: string = null;
    private _____ownerId: string = null;
    private _____creatorId: string = null;
    private _____state: string = null;
    private _____operation: string = null;
    private _____tts: Long = null;
    private _____sequence: number = null;
    private _____ttsTo: Long = null;
    private ___id: string = null;
    private ___firstName: string = null;
    private ___name: string = null;
    private ___dateOfBirth: Date = null;
    private ___dateOfDeath: Date = null;

    public get __typeId(): string {
        return Patients.__typeId;
    }

    public get __typeName(): string {
        return Patients.__typeName;
    }

    public get __domainId(): string {
        return this._____domainId;
    }

    public set __domainId(value: string) {
        this._____domainId = value;
    }

    public get __ownerId(): string {
        return this._____ownerId;
    }

    public set __ownerId(value: string) {
        this._____ownerId = value;
    }

    public get __creatorId(): string {
        return this._____creatorId;
    }

    public set __creatorId(value: string) {
        this._____creatorId = value;
    }

    public get __state(): string {
        return this._____state;
    }

    public set __state(value: string) {
        this._____state = value;
    }

    public get __operation(): string {
        return this._____operation;
    }

    public set __operation(value: string) {
        this._____operation = value;
    }

    public get __tts(): Long {
        return this._____tts;
    }

    public set __tts(value: Long) {
        this._____tts = value;
    }

    public get __sequence(): number {
        return this._____sequence;
    }

    public set __sequence(value: number) {
        this._____sequence = value;
    }

    public get __ttsTo(): Long {
        return this._____ttsTo;
    }

    public set __ttsTo(value: Long) {
        this._____ttsTo = value;
    }

    public get id(): string {
        if (this.___id === null) {this.___id = this.createId();}
        return this.___id;
    }

    public set id(value: string) {
        this.___id = value;
    }

    public get firstName(): string {
        return this.___firstName;
    }

    public set firstName(value: string) {
        this.___firstName = value;
    }

    public get name(): string {
        return this.___name;
    }

    public set name(value: string) {
        this.___name = value;
    }

    public get dateOfBirth(): Date {
        return this.___dateOfBirth;
    }

    public set dateOfBirth(value: Date) {
        this.___dateOfBirth = value;
    }

    public get dateOfDeath(): Date {
        return this.___dateOfDeath;
    }

    public set dateOfDeath(value: Date) {
        this.___dateOfDeath = value;
    }

    protected createId(): string {
        var UUID = require('uuid-js');
        return UUID.create(1);
    }

    public static fromJson (json: {}):concrete_Patients {
        if (!json) return null;

        let object = new concrete_Patients();
        object.setJson(json);

        return object;
    }

    protected setJson (json: {}): void {
        if (json) {
            this.__domainId = json['__domainId'] != null ? json['__domainId'] : null;
            this.__ownerId = json['__ownerId'] != null ? json['__ownerId'] : null;
            this.__creatorId = json['__creatorId'] != null ? json['__creatorId'] : null;
            this.__state = json['__state'] != null ? json['__state'] : null;
            this.__operation = json['__operation'] != null ? json['__operation'] : null;
            this.__tts = json['__tts'] != null ? Long.fromString(json['__tts']) : null;
            this.__sequence = json['__sequence'] != null ? json['__sequence'] : null;
            this.__ttsTo = json['__ttsTo'] != null ? Long.fromString(json['__ttsTo']) : null;
            this.id = json['id'] != null ? json['id'] : null;
            this.firstName = json['firstName'] != null ? json['firstName'] : null;
            this.name = json['name'] != null ? json['name'] : null;
            this.dateOfBirth = json['dateOfBirth'] != null ? new Date(parseInt(json['dateOfBirth'].substring(0, 4)), parseInt(json['dateOfBirth'].substring(5, 7)), parseInt(json['dateOfBirth'].substring(8, 10))) : null;
            this.dateOfDeath = json['dateOfDeath'] != null ? new Date(parseInt(json['dateOfDeath'].substring(0, 4)), parseInt(json['dateOfDeath'].substring(5, 7)), parseInt(json['dateOfDeath'].substring(8, 10))) : null;
        }
    }

    protected writeJsonMembers(json: {}): void {
        {
            json['__tts'] = this.__tts !== null ? this.__tts.toString() : null;
        }
        {
            json['id'] = this.id;
        }
        {
            json['firstName'] = this.firstName;
        }
        {
            json['name'] = this.name;
        }
        {
            json['dateOfBirth'] = this.dateOfBirth !== null ? this.dateOfBirth.getFullYear() +"-" + ("0" + (this.dateOfBirth.getMonth() + 1)).slice(-2) + "-" + ("0" + this.dateOfBirth.getDate()).slice(-2) : null;
        }
        {
            json['dateOfDeath'] = this.dateOfDeath !== null ? this.dateOfDeath.getFullYear() +"-" + ("0" + (this.dateOfDeath.getMonth() + 1)).slice(-2) + "-" + ("0" + this.dateOfDeath.getDate()).slice(-2) : null;
        }
    }

    public toJson(injectType?:boolean): {} {
        let json = {};
        json['__typeId'] = this.__typeId;
        this.writeJsonMembers(json);
        return json;
    }

    public toString(): string {
        return JSON.stringify(this.toJson());
    }

}
