// Generated by rocketdb: Do not edit this code!

import {PatientMedication as concrete_PatientMedication} from '../PatientMedication';
import * as Long from 'long';
import {BigInteger} from 'big-integer';
import * as bigInt from 'big-integer';

export abstract class PatientMedication {

    public static readonly __typeId: string = "9793afdb-acae-11e9-a183-cfa452e7415c";
    public static readonly __typeName: string = "pharmacy.PatientMedication";

    private _____domainId: string = null;
    private _____ownerId: string = null;
    private _____creatorId: string = null;
    private _____state: string = null;
    private _____operation: string = null;
    private _____tts: Long = null;
    private _____sequence: number = null;
    private _____ttsTo: Long = null;
    private ___id: string = null;
    private ___prescriptionDate: Date = null;
    private ___prescriptionEnd: Date = null;
    private ___posologyMorning: BigInteger = null;
    private ___posologyMidday: BigInteger = null;
    private ___posologyEvening: BigInteger = null;
    private ___posologyNight: BigInteger = null;
    private ___prescribedToId: string = null;
    private ___basedForId: string = null;

    public get __typeId(): string {
        return PatientMedication.__typeId;
    }

    public get __typeName(): string {
        return PatientMedication.__typeName;
    }

    public get __domainId(): string {
        return this._____domainId;
    }

    public set __domainId(value: string) {
        this._____domainId = value;
    }

    public get __ownerId(): string {
        return this._____ownerId;
    }

    public set __ownerId(value: string) {
        this._____ownerId = value;
    }

    public get __creatorId(): string {
        return this._____creatorId;
    }

    public set __creatorId(value: string) {
        this._____creatorId = value;
    }

    public get __state(): string {
        return this._____state;
    }

    public set __state(value: string) {
        this._____state = value;
    }

    public get __operation(): string {
        return this._____operation;
    }

    public set __operation(value: string) {
        this._____operation = value;
    }

    public get __tts(): Long {
        return this._____tts;
    }

    public set __tts(value: Long) {
        this._____tts = value;
    }

    public get __sequence(): number {
        return this._____sequence;
    }

    public set __sequence(value: number) {
        this._____sequence = value;
    }

    public get __ttsTo(): Long {
        return this._____ttsTo;
    }

    public set __ttsTo(value: Long) {
        this._____ttsTo = value;
    }

    public get id(): string {
        if (this.___id === null) {this.___id = this.createId();}
        return this.___id;
    }

    public set id(value: string) {
        this.___id = value;
    }

    public get prescriptionDate(): Date {
        return this.___prescriptionDate;
    }

    public set prescriptionDate(value: Date) {
        this.___prescriptionDate = value;
    }

    public get prescriptionEnd(): Date {
        return this.___prescriptionEnd;
    }

    public set prescriptionEnd(value: Date) {
        this.___prescriptionEnd = value;
    }

    public get posologyMorning(): BigInteger {
        return this.___posologyMorning;
    }

    public set posologyMorning(value: BigInteger) {
        this.___posologyMorning = value;
    }

    public get posologyMidday(): BigInteger {
        return this.___posologyMidday;
    }

    public set posologyMidday(value: BigInteger) {
        this.___posologyMidday = value;
    }

    public get posologyEvening(): BigInteger {
        return this.___posologyEvening;
    }

    public set posologyEvening(value: BigInteger) {
        this.___posologyEvening = value;
    }

    public get posologyNight(): BigInteger {
        return this.___posologyNight;
    }

    public set posologyNight(value: BigInteger) {
        this.___posologyNight = value;
    }

    public get prescribedToId(): string {
        return this.___prescribedToId;
    }

    public set prescribedToId(value: string) {
        this.___prescribedToId = value;
    }

    public get basedForId(): string {
        return this.___basedForId;
    }

    public set basedForId(value: string) {
        this.___basedForId = value;
    }

    protected createId(): string {
        var UUID = require('uuid-js');
        return UUID.create(1);
    }

    public static fromJson (json: {}):concrete_PatientMedication {
        if (!json) return null;

        let object = new concrete_PatientMedication();
        object.setJson(json);

        return object;
    }

    protected setJson (json: {}): void {
        if (json) {
            this.__domainId = json['__domainId'] != null ? json['__domainId'] : null;
            this.__ownerId = json['__ownerId'] != null ? json['__ownerId'] : null;
            this.__creatorId = json['__creatorId'] != null ? json['__creatorId'] : null;
            this.__state = json['__state'] != null ? json['__state'] : null;
            this.__operation = json['__operation'] != null ? json['__operation'] : null;
            this.__tts = json['__tts'] != null ? Long.fromString(json['__tts']) : null;
            this.__sequence = json['__sequence'] != null ? json['__sequence'] : null;
            this.__ttsTo = json['__ttsTo'] != null ? Long.fromString(json['__ttsTo']) : null;
            this.id = json['id'] != null ? json['id'] : null;
            this.prescriptionDate = json['prescriptionDate'] != null ? new Date(parseInt(json['prescriptionDate'].substring(0, 4)), parseInt(json['prescriptionDate'].substring(5, 7)), parseInt(json['prescriptionDate'].substring(8, 10))) : null;
            this.prescriptionEnd = json['prescriptionEnd'] != null ? new Date(parseInt(json['prescriptionEnd'].substring(0, 4)), parseInt(json['prescriptionEnd'].substring(5, 7)), parseInt(json['prescriptionEnd'].substring(8, 10))) : null;
            this.posologyMorning = json['posologyMorning'] != null ? bigInt(json['posologyMorning']) : null;
            this.posologyMidday = json['posologyMidday'] != null ? bigInt(json['posologyMidday']) : null;
            this.posologyEvening = json['posologyEvening'] != null ? bigInt(json['posologyEvening']) : null;
            this.posologyNight = json['posologyNight'] != null ? bigInt(json['posologyNight']) : null;
            this.prescribedToId = json['prescribedToId'] != null ? json['prescribedToId'] : null;
            this.basedForId = json['basedForId'] != null ? json['basedForId'] : null;
        }
    }

    protected writeJsonMembers(json: {}): void {
        {
            json['__tts'] = this.__tts !== null ? this.__tts.toString() : null;
        }
        {
            json['id'] = this.id;
        }
        {
            json['prescriptionDate'] = this.prescriptionDate !== null ? this.prescriptionDate.getFullYear() +"-" + ("0" + (this.prescriptionDate.getMonth() + 1)).slice(-2) + "-" + ("0" + this.prescriptionDate.getDate()).slice(-2) : null;
        }
        {
            json['prescriptionEnd'] = this.prescriptionEnd !== null ? this.prescriptionEnd.getFullYear() +"-" + ("0" + (this.prescriptionEnd.getMonth() + 1)).slice(-2) + "-" + ("0" + this.prescriptionEnd.getDate()).slice(-2) : null;
        }
        {
            json['posologyMorning'] = this.posologyMorning !== null ? this.posologyMorning.toString() : null;
        }
        {
            json['posologyMidday'] = this.posologyMidday !== null ? this.posologyMidday.toString() : null;
        }
        {
            json['posologyEvening'] = this.posologyEvening !== null ? this.posologyEvening.toString() : null;
        }
        {
            json['posologyNight'] = this.posologyNight !== null ? this.posologyNight.toString() : null;
        }
        {
            json['prescribedToId'] = this.prescribedToId;
        }
        {
            json['basedForId'] = this.basedForId;
        }
    }

    public toJson(injectType?:boolean): {} {
        let json = {};
        json['__typeId'] = this.__typeId;
        this.writeJsonMembers(json);
        return json;
    }

    public toString(): string {
        return JSON.stringify(this.toJson());
    }

}
