// Generated by rocketdb: Do not edit this code!

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

using System.Linq;
using System;

namespace Pharmacy.Types.Module.Base
{
    #pragma warning disable 3021

    public abstract class Configuration
    {

        [CLSCompliantAttribute(false)]
        public const string __typeId = "38f9941c-5d29-11e9-91b2-4b4f2bb00878";
        [CLSCompliantAttribute(false)]
        public const string __typeName = "pharmacy.module.Configuration";

        private string __domainId;
        private string __ownerId;
        private string __creatorId;
        private string __state;
        private string __operation;
        private long? __tts;
        private int? __sequence;
        private long? __ttsTo;
        private string __id;
        private string __moduleId;
        private string __name;
        private bool __active;

        [CLSCompliantAttribute(false)]
        public virtual string __TypeId {
            get { return __typeId; }
        }

        [CLSCompliantAttribute(false)]
        public virtual string __TypeName {
            get { return __typeName; }
        }

        [CLSCompliantAttribute(false)]
        public virtual string __DomainId {
            get { return __domainId; }
            private set { __domainId = value; }
        }

        [CLSCompliantAttribute(false)]
        public virtual string __OwnerId {
            get { return __ownerId; }
            private set { __ownerId = value; }
        }

        [CLSCompliantAttribute(false)]
        public virtual string __CreatorId {
            get { return __creatorId; }
            private set { __creatorId = value; }
        }

        [CLSCompliantAttribute(false)]
        public virtual string __State {
            get { return __state; }
            private set { __state = value; }
        }

        [CLSCompliantAttribute(false)]
        public virtual string __Operation {
            get { return __operation; }
            private set { __operation = value; }
        }

        [CLSCompliantAttribute(false)]
        public virtual long? __Tts {
            get { return __tts; }
            private set { __tts = value; }
        }

        [CLSCompliantAttribute(false)]
        public virtual int? __Sequence {
            get { return __sequence; }
            private set { __sequence = value; }
        }

        [CLSCompliantAttribute(false)]
        public virtual long? __TtsTo {
            get { return __ttsTo; }
            private set { __ttsTo = value; }
        }

        [CLSCompliantAttribute(false)]
        public virtual string __Id {
            get { return __id; }
            private set { __id = value; }
        }

        [CLSCompliantAttribute(false)]
        public virtual string __ModuleId {
            get { return __moduleId; }
            private set { __moduleId = value; }
        }

        [CLSCompliantAttribute(false)]
        public virtual string __Name {
            get { return __name; }
            private set { __name = value; }
        }

        [CLSCompliantAttribute(false)]
        public virtual bool __Active {
            get { return __active; }
            private set { __active = value; }
        }

        public static Pharmacy.Types.Module.Configuration FromJson(JObject jo)
        {
            if (jo == null)
            {
                return null;
            }
            Pharmacy.Types.Module.Configuration obj = new Pharmacy.Types.Module.Configuration();
            obj.SetJson(jo);
            return obj;
        }

        protected virtual void SetJson(JObject jo)
        {
            this.__DomainId = (string)jo["__domainId"];
            this.__OwnerId = (string)jo["__ownerId"];
            this.__CreatorId = (string)jo["__creatorId"];
            this.__State = (string)jo["__state"];
            this.__Operation = (string)jo["__operation"];
            this.__Tts = (long?)jo["__tts"];
            this.__Sequence = (int?)jo["__sequence"];
            this.__TtsTo = (long?)jo["__ttsTo"];
            this.__Id = (string)jo["__id"];
            this.__ModuleId = (string)jo["__moduleId"];
            this.__Name = (string)jo["__name"];
            this.__Active = (bool)jo["__active"];
        }

        public virtual JObject ToJson()
        {
            JTokenWriter writer = new JTokenWriter();
            ToJson(writer, false);
            return (JObject)writer.Token;
        }

        public virtual void ToJson(JsonWriter writer, bool injectType)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("__typeId");
            writer.WriteValue(this.__TypeId);
            WriteMembers(writer);
            writer.WriteEndObject();
        }

        protected virtual void WriteMembers(JsonWriter writer)
        {
            {
                writer.WritePropertyName("__tts");
                writer.WriteValue(this.__Tts);
            }
            {
                writer.WritePropertyName("__id");
                writer.WriteValue(this.__Id);
            }
            {
                writer.WritePropertyName("__moduleId");
                writer.WriteValue(this.__ModuleId);
            }
            {
                writer.WritePropertyName("__name");
                writer.WriteValue(this.__Name);
            }
            {
                writer.WritePropertyName("__active");
                writer.WriteValue(this.__Active);
            }
        }

        public virtual void Validate()
        {
        }

        public override string ToString()
        {
            return ToJson().ToString();
        }

    }
}
